educator/urls.py
from django.urls import path
from . import views

app_name = "educator"
urlpatterns = [
    path("", views.index, name="index"),
    path("records", views.records, name="records"),
    path("logout", views.logout, name="logout"),
    path("profile", views.profile, name="profile"),
    path("settings", views.settings, name="settings"),
    path("enroll", views.enroll, name="enroll"),
    path("report", views.report, name="report"),
    path("grading", views.grading, name="grading")
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("enroll", views.enroll, name="enroll"),
    path("about", views.about, name="about"),
    path("register", views.register, name="register"),
    path("login", views.login, name="login")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
    path('educator/', include("educator.urls"))
]

educator/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

educator/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def logout(request):
    pass

def index(request):
    return render(request, "teacher/index.html")

def profile(request):
    pass

def records(request):
    return render(request, "teacher/records.html")

def settings(request):
    pass

def enroll(request):
    pass

def report(request):
    pass

def grading(request):
    pass

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django import forms
from . import sform
import pandas as pd


# Create your views here.
def index(request):
    return render(request, "unlogged/index.html")

def enroll(request):
    #country_file = pd.read_csv('countryInfo.txt', delimiter='\t')
    return render(request, "unlogged/enroll.html")

def about(request):
    return render(request, "unlogged/about.html")

def register(request):
    if request.method == "POST":
        form = forms.Form(request.POST)
        if form.is_valid():
            return render(request, "unlogged/register2.html")
        else:
            return HttpResponse("bad")
    form = sform.register1_form()        
    return render(request, "unlogged/register1.html", {
        "form": form
    })

def login(request):
    return render(request, 'unlogged/login.html')

educator/templates/layout.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>{% block title%}{% endblock%}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link href="{% static 'styles.css' %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <nav style="background-color: #261A73; padding: 10px;">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <h1>FPS</h1>
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'educator:index' %}" class="nav-link px-2 text-white">Home</a></li>
                    <li><a href="{% url 'educator:records' %}" class="nav-link px-2 text-white">Student Records</a></li>
                    <li><a href="{% url 'educator:grading' %}" class="nav-link px-2 text-white">Grading</a></li>
                    <li><a href="{% url 'educator:enroll' %}" class="nav-link px-2 text-white">Enroll Students</a></li>
                    <li><a href="{% url 'educator:report' %}" class="nav-link px-2 text-white">Report Generation</a></li>
                    <li><a href="{% url 'educator:records' %}" class="nav-link px-2 text-white">Teacher Records</a></li>
                </ul>

                <div class="text-end">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="profile" style="background-color: #8A86A6;">
                             Account ☰
                        </a>
                      
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a></li>
                          <li><a class="dropdown-item" href="{% url 'home:profile' %}">Profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'home:settings' %}">Settings</a></li>
                        </ul>
                      </div>
                </div>
              </div>
            </div>
        </nav>
    </head>
    <body>
        {% block main %}
        {% endblock %}
        
        <!--Add footer-->
        <div style="background-color: #261A73; color: white; padding:50px">
            <footer class="py-5">
              <div class="row">
                <div class="col-6 col-md-2 mb-3">
                  <h5>Explore</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'home:index' %}" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Using FPS</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'home:about' %}" class="nav-link p-0 text-muted">About</a></li>
                  </ul>
                </div>
          
                <div class="col-md-5 offset-md-1 mb-3">
                  <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                      <label for="newsletter1" class="visually-hidden">Email address</label>
                      <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                      <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                  </form>
                </div>
              </div>
          
              <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p>© 2023 Malik Delana Taiwo. All rights reserved.</p>
                <ul class="list-unstyled d-flex">
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
                </ul>
              </div>
            </footer>
          </div>
    </body>

</html>

home/templates/layout.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>{% block title%}{% endblock%}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link href="{% static 'styles.css' %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <nav style="background-color: #261A73; padding: 10px;">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <h1>FPS</h1>
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'home:index' %}" class="nav-link px-2 text-white">Home</a></li>
                    <li><a href="{% url 'home:about' %}" class="nav-link px-2 text-white">About Us</a></li>
                    <li><a class="nav-link px-2 text-white" href="{% url 'home:enroll' %}">Enroll your school</a></li>
                </ul>

                <div class="text-end">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="profile" style="background-color: #8A86A6;">
                             Account ☰
                        </a>
                      
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'home:login' %}">Login</a></li>
                          <li><a class="dropdown-item" href="{% url 'home:register' %}">Register</a></li>
                        </ul>
                      </div>
                </div>
              </div>
            </div>
        </nav>
    </head>
    <body>
        {% block main %}
        {% endblock %}
        
        <!--Add footer-->
        <div style="background-color: #261A73; color: white; padding:50px">
            <footer class="py-5">
              <div class="row">
                <div class="col-6 col-md-2 mb-3">
                  <h5>Explore</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'home:index' %}" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Using FPS</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'home:about' %}" class="nav-link p-0 text-muted">About</a></li>
                  </ul>
                </div>
          
                <div class="col-md-5 offset-md-1 mb-3">
                  <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                      <label for="newsletter1" class="visually-hidden">Email address</label>
                      <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                      <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                  </form>
                </div>
              </div>
          
              <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p>© 2023 Malik Delana Taiwo. All rights reserved.</p>
                <ul class="list-unstyled d-flex">
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                  <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
                </ul>
              </div>
            </footer>
          </div>
    </body>

</html>